[package]
name = "count-chars"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
globwalk = "0.8.1"
unicode-normalization = "0.1.22"
unicode-segmentation = "1.10.0"
unicode_categories = "0.1.1"
